services:
  - type: web
    name: dermai-api
    runtime: python
    pythonVersion: 3.11
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: FIREBASE_PROJECT_ID
        value: ai-face-health-analyzer
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@ai-face-health-analyzer.iam.gserviceaccount.com
      - key: FIREBASE_DATABASE_URL
        value: https://ai-face-health-analyzer.firebaseio.com
      - key: ENVIRONMENT
        value: production
